---
title: "Pharmacy Warfarin Dosing Service"
output: 
  flexdashboard::flex_dashboard:
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(lubridate)
library(stringr)
library(edwr)
library(dygraphs)
library(xts)
library(RColorBrewer)

dir_raw <- "../data/raw/mbo"

# get all warfarin and consult orders
data_order_actions <- read_data(dir_raw, "order-actions", FALSE) %>%
    as.order_action() %>%
    filter(action.type == "Order" | action.type == "Complete",
           action.provider.role != "HIN Team Licensed",
           action.provider.role != "DBA") %>%
    mutate(action.date = floor_date(action.datetime, unit = "day"),
           consult = str_detect(order, "Dosing"))

patient_groups <- data_order_actions %>%
    group_by(millennium.id) %>%
    summarize_at("consult", sum) %>%
    dmap_at("consult", ~ .x > 1)

# make tidy data set
df <- data_order_actions %>%
    distinct(millennium.id, action.date, consult) %>%
    group_by(millennium.id, action.date) %>%
    mutate(value = TRUE,
           consult = if_else(consult == TRUE, "consult", "warfarin")) %>%
    spread(consult, value) %>%
    mutate(warfarin = if_else(consult == TRUE & is.na(warfarin), TRUE, warfarin)) %>%
    gather(order, value, consult, warfarin) %>%
    filter(!is.na(value)) %>%
    group_by(millennium.id, action.date, order) %>%
    summarize(n = n()) %>%
    group_by(action.date, order) %>%
    summarize(n = n()) %>%
    spread(order, n) %>%
    mutate(warfarin = if_else(is.na(consult), warfarin, warfarin - consult)) %>%
    gather(order, n, -action.date) %>%
    mutate(n = coalesce(n, 0L)) %>%
    spread(order, n) %>%
    filter(action.date >= mdy("7/1/2014"),
           action.date <= mdy("2/28/2017"))

ts <- as.matrix(df[, 2:3]) %>% 
    as.xts(order.by = df$action.date, tzone = "US/Central")

dyg <- dygraph(ts, main = "Daily Warfarin Orders") %>%
    dySeries("consult", label = "Pharmacy") %>%
    dySeries("warfarin", label = "Traditional") 

# x <- filter(data_order_actions, action.date == mdy("02/27/2015"),
            # action.provider.role != "HIN Team Licensed")
```

Utilization
========================================================

### Utilization of Pharmacy Warfarin Dosing Service

```{r}
start.range <- c(max(df$action.date) - months(12), max(df$action.date))

dyg %>%
    dyOptions(colors = brewer.pal(3, "Set1")) %>%
    dyRoller(rollPeriod = 5) %>%
    dyRangeSelector() %>%
    dyRangeSelector(start.range)

```

> Data presented as the average over a rolling period of days (default is 5). The rolling period can be adjusted using the text box in the lower left corner of the figure. Set the value to 1 to show individual daily values. Adjust the time period being displayed using the selector at the bottom of the figure.

```{r, eval=FALSE, echo=FALSE, fig.width=6, fig.height=4.5}
df %>%
    # filter(action.date >= mdy("1/1/2016"), action.date < mdy("2/1/2017")) %>%
    gather(service, num, consult:warfarin) %>% 
    ggplot(aes(x = action.date, y = num)) +
    geom_line(aes(color = service), alpha = 0.6) +
    geom_smooth(aes(color = service))
```

```{r}
library(forecast)
ts_consults <- as.matrix(df[, 2]) %>% 
    as.xts(order.by = df$action.date, tzone = "US/Central")

a <- auto.arima(ts_consults)

f <- forecast(ts_consults, h = 365 / 2, model = a)

plot(f)
```

```{r}
keep_visits <- c("Inpatient", "Emergency", "Observation", "Inpatient Snf", "Inpatient Rehab", "Inpatient Psych", "Inpatient LTC", "EC Fast ER Care", "72 Hour ER")

dc_home <- c("Home or Self Care", "Home Care with Home Health", "Left Against Medical Advise", "DC TO HOME/SELF CARE")

patients <- read_data(dir_raw, "patients", FALSE) %>%
    as.patients() %>%
    select(millennium.id, discharge.datetime) 

encounters <- read_data(dir_raw, "encounters") %>%
    as.encounters()

# keep only patients that went home
tmp_home <- patients %>%
    inner_join(encounters, by = "millennium.id") %>%
    filter(disposition %in% dc_home) %>%
    select(millennium.id, discharge.datetime) 

# find the time from index visit
revisit <- encounters %>%
    left_join(tmp_home, by = "millennium.id") %>%
    mutate(index_visit_id = if_else(!is.na(discharge.datetime), millennium.id, NA_character_)) %>%
    arrange(person.id, admit.datetime) %>%
    filter(visit.type %in% keep_visits) %>%
    group_by(person.id) %>%
    fill(discharge.datetime, index_visit_id) %>%
    filter(!is.na(discharge.datetime)) %>%
    mutate(revisit_days = difftime(admit.datetime, discharge.datetime, units = "days")) %>%
    filter(revisit_days > 0, revisit_days <= 30) %>%
    distinct(person.id, index_visit_id, visit.type, .keep_all = TRUE) %>%
    rename(revisit_id = millennium.id)

# ed visit -> transferred and admitted ?
```

```{r}
data_revisit <- patient_groups %>%
    left_join(patients, by = "millennium.id") %>%
    left_join(revisit, by = c("millennium.id" = "index_visit_id", "discharge.datetime")) %>%
    mutate(revisit = !is.na(visit.type),
           readmit = visit.type == "Inpatient",
           er = visit.type == "Emergency",
           obs = visit.type == "Observation",
           dc_year = floor_date(discharge.datetime, "year"),
           dc_month = floor_date(discharge.datetime, "month")) %>%
    filter(!is.na(consult),
           dc_month < mdy("3/1/2017")) 
```

```{r}
data_revisit %>%
    group_by(consult, dc_year, dc_month) %>%
    filter(!is.na(dc_month)) %>%
    summarize_at("revisit", funs(sum(., na.rm = TRUE) / n() * 100)) %>%
    ggplot(aes(x = dc_month, y = revisit, fill = consult)) +
    geom_bar(stat = "identity", position = "dodge") +
    facet_wrap(~ dc_year, scales = "free_x") +
    coord_cartesian(ylim = c(0, 25))
```

```{r}
library(broom)

select(data_revisit, dc_year, consult, revisit) %>%
    dmap_at("consult", ~ if_else(.x, "pharmacy", "traditional")) %>%
    dmap_at("revisit", ~ if_else(.x, "revisit", "none")) %>%
    slice_rows("dc_year") %>%
    by_slice(~ tidy(chisq.test(.x$consult, .x$revisit)), .collate = "rows") %>%
    knitr::kable(digits = 3)
```

```{r}
data_revisit %>%
    group_by(consult, dc_year, dc_month) %>%
    filter(!is.na(dc_month)) %>%
    summarize_at("readmit", funs(sum(., na.rm = TRUE) / n() * 100)) %>%
    ggplot(aes(x = dc_month, y = readmit, fill = consult)) +
    geom_bar(stat = "identity", position = "dodge") +
    facet_wrap(~ dc_year, scales = "free_x") +
    coord_cartesian(ylim = c(0, 25))
```

```{r}
select(data_revisit, dc_year, consult, readmit) %>%
    dmap_at("consult", ~ if_else(.x, "pharmacy", "traditional")) %>%
    dmap_at("readmit", ~ if_else(.x, "readmit", "none")) %>%
    slice_rows("dc_year") %>%
    by_slice(~ tidy(chisq.test(.x$consult, .x$readmit)), .collate = "rows") %>%
    knitr::kable(digits = 3)
```

```{r}
data_revisit %>%
    group_by(consult, dc_year, dc_month) %>%
    filter(!is.na(dc_month)) %>%
    summarize_at("er", funs(sum(., na.rm = TRUE) / n() * 100)) %>%
    ggplot(aes(x = dc_month, y = er, fill = consult)) +
    geom_bar(stat = "identity", position = "dodge") +
    facet_wrap(~ dc_year, scales = "free_x") +
    coord_cartesian(ylim = c(0, 25))
```

```{r}
select(data_revisit, dc_year, consult, er) %>%
    dmap_at("consult", ~ if_else(.x, "pharmacy", "traditional")) %>%
    dmap_at("er", ~ if_else(.x, "er", "none")) %>%
    slice_rows("dc_year") %>%
    by_slice(~ tidy(chisq.test(.x$consult, .x$er)), .collate = "rows") %>%
    knitr::kable(digits = 3)
```

```{r}
data_revisit %>%
    group_by(consult, dc_year, dc_month) %>%
    filter(!is.na(dc_month)) %>%
    summarize_at("obs", funs(sum(., na.rm = TRUE) / n() * 100)) %>%
    ggplot(aes(x = dc_month, y = obs, fill = consult)) +
    geom_bar(stat = "identity", position = "dodge") +
    facet_wrap(~ dc_year, scales = "free_x") +
    coord_cartesian(ylim = c(0, 25))
```

```{r}
select(data_revisit, dc_year, consult, obs) %>%
    dmap_at("consult", ~ if_else(.x, "pharmacy", "traditional")) %>%
    dmap_at("obs", ~ if_else(.x, "obs", "none")) %>%
    slice_rows("dc_year") %>%
    by_slice(~ tidy(chisq.test(.x$consult, .x$obs)), .collate = "rows") %>%
    knitr::kable(digits = 3)
```
